#!/bin/bash
if [ $# -eq 0 ]
then
  setOn="true"
else
  if [ "$1" == "e" ]
  then
    setOn="true"
  else
    setOn="false"
  fi
fi
echo "setON: ${setOn}" 

if [ "${setOn}" == "true" ]
then
  echo "Enabling Ethernet connection with DHCP "
  networksetup -setdhcp Ethernet
else
  echo "Disabling Ethernet connection "
  networksetup -setv4off Ethernet
fi

